name: Build Signed APK

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate Release Info
        id: release_info
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="build-$(date +'%Y%m%d-%H%M%S')"
          fi

          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Using tag: $TAG"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore.jks

      - name: Build Release APK
        run: |
          ./gradlew assembleRelease \
            -PAPI_HOST=${API_HOST} \
            -PSTORE_FILE=keystore.jks \
            -PSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} \
            -PKEY_ALIAS=${{ secrets.KEY_ALIAS }} \
            -PKEY_PASSWORD=${{ secrets.KEY_PASSWORD }} \
            --configuration-cache

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release_info.outputs.tag }}
          name: Release ${{ steps.release_info.outputs.tag }}
          generate_release_notes: true
          files: |
            app/build/outputs/apk/release/*arm64*.apk
            app/build/outputs/apk/release/*armeabi*.apk
            app/build/outputs/apk/release/*universal*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}